name: koroutine-web-crawler/lint

on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    strategy:
      matrix:
        go: [ '1.22.x' ]
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@main
      
      # Setup our base Go environment 🧬
      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        
      # Install Go Staticcheck
      - name: Install Go Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      # Install Go Critic
      - name: Install Go Critic
        run: go install -v github.com/go-critic/go-critic/cmd/gocritic@latest

      # Run Go Test
      - name: Go Format
        run: go fmt ./...
      
      # Run Go Vet
      - name: Go Vet
        run: go vet ./...

      # Run Go Static Checks
      - name: Go Static Checks
        run: staticcheck ./...

      # Run Go Critic
      - name: Go Critic
        run: gocritic check ./...